language: java
jdk: 
 - openjdk11
addons:
  sonarcloud:
    organization: "akiwicoder"
    token:
      secure: "GqG4P+ssKV72e+q6+XBfuZ7As9fYLw0ZQZf7cKky4QS7NpKrXWkAx0FgfD2IYzb0UAf0znKRTEaCHJUu54Y/FCbOizFJby4hUKDLCLlho4sRrHzEu09eIeXydmUBY4ROmqfoDjOuvRgQ6hY4NoBVKTEQjb7PFCi7KFrmipcG1G/JN0qHBxLmM0OZbbVZlh84W8L2c8Qvt7R3A48iv6I64fqEPHr6spy25h54bOfo1nOiPXdmB5eMQc6RRInYpmUG1V9JkRprS5imKSZQoRHyhX08SecodYf6Nx+DYwCGP8Vv//0P+Yezl5UfZCbIzFd/wHUxiKpJnH1HE/j8RXRv3JTh0p+Gry4xX3myMMqD4UlVHc+66QC44Qli6djAMPJj7LRxWeIgdemTA90bX6Qd3lVxmhbwRfn/8xPphgLfLBmmNQ5uV1Yi2Bw2hbqv5X6iqOMZpgfh0R8v8oufkcZBstIgJwVc4XYbo6w3ov6mWHAuza2TAKEqc2UEeibFRWvwpYcT1XawN4C2FROwQRd8ZVij1fdBdAmIQtAHhmd+ECDfdKAyk7GVHRJBpm2oS1qBiShLbfEwD1b3gc0Bu5unq0jArbk26NthhokcSur+m2gQUfuPf+iFkynVEfVqYqmv5qKbyOUGonUw6TUkRbs4JLyC3sz3m9M4YsfSZgqKdOI="
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=AKiwiCoder_mud
